name: Build

on:
  pull_request:
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Prepare Env
      run: bash scripts/prepare_environ.sh

    - name: Test
      working-directory: /home/runner/go/src/github.com/meshplus/consensus
      run:  make all

    - name: Post
      working-directory: /home/runner/go/src/github.com/meshplus/consensus
      run: ./scripts/post.sh
